/* Fallout Weapons */
//my house rules doesn't account for Energy Weapons for their usage, only to maintain them so they are all mixed in
/* Handmade Guns */
var handmade = ["Pipe Pistol - Break Action 9mm",
"Derringer - .32",
"Pipe Rifle - Break Action 9mm",
"Pipe Rifle - Break Action 10mm",
"Pipe Rifle - Bolt Action 10mm",
"Shotgonne - Breach Load .44",
"Lever Action - .50 AE",
"Hunting Rifle - .50 AE",
"Kalthoff - Lorenzo Repeating Flintlock Pistol- Powder & Ball",
"Kalthoff - Lorenzo Repeating Flintlock Rifle - Powder & Ball"];

var falloutUniqueweapon = ["That Gun - 5.56mm",
"Spasm NeuroDisruptor - SEC/MFC",
"Ripper - SEC",
"Super Cattle Prod - SEC",
"Power Fist - SEC",
"Super Sledge - SEC",
"Turbo super sledge - Fuel",
"Plasma Saw - MFC",
"Tesla cleaver - SEC",
"Thermic Lance - MFC",
"Arc Welder - MFC",
"H&H Tools Nail Gun - 9 inch nails",
"ARTEMIS Rail Gun - 2mm/15mm EC",
"APOLLO Laser Gun - SEC",
"Cryogenic Fluid Recipe",
"Heckler - 40mm/20mm",
"PPK 12 Gauss - SEC & 2mm EC",
"Wattz 2500 Laser Rifle - MFC",
"Gyrojet Rifle - Handmade",
"Gyrojet Pistol - Handmade",
"Sprtel-Wood 9700 - MFC"];

/* Pre-historic crap */
var falloutPistols = ["Browning Hi-Power - 9mm",
"Smith & Wesson .32 pistol - .32",
"Barretta 92fs - 9mm",
"Shanxi Type 17 -10mm", 
"Colt 6520 - 10mm",
"Colt M1911 .45 - .45",
"Casull Revolver - .45",
"Desert Eagle .44 - .44",
"Smith & Wesson Model 29 - .44",
"Wattz 500 Laser Pistol - SEC",
"Sig-Sauer Auto Pistol - 14mm",
"Colt Python - .357",
"Mateba Autorevolver - .357",
"Desert Eagle .50 - .50 AE",
"Colt Delta Elite - 10mm",
"Zhu-Rong v418 - 10mm",
"Wattz 1000 Laser Pistol - SEC",
"Van Graff Wattz 500 Laser Pistol - SEC",
"Glock 86 Plasma Defender - SEC",
"YK32 Pulse Pistol - SEC",
"C4 Block",
"C70 Block"];


var falloutSMGs = ["MP5 Navy - 9mm",
"MP7 Delta Elite - 10mm",
"Tommy Gun - .45",
"Walther MPL - 9mm",
"Jatimatic '67 - 9mm",
"Uzi - 10mm",
"P90 - 5.56mm",
"Grease Gun - .45",
"Gun Runners Automat - .50 AE",
"PPK 36 Gauss - SEC & 2mm EC",
"PP-2070 - 9mm",
"MP 9 - 10mm",
"Van Graff Laser RCW - SECs",
"Sig Sauer FA - 14mm",
"Gun Runners Hunting SMG - 50 AE"];

var falloutRifles = ["Varmint rifle - 5.56mm",
"Hunting rifle - 7.62mm",
"AK-112 - 5mm",
"AK-2064 - 14mm",
"FN FAL - 7.62mm",
"R91 AR - 5.56mm",
"G11 - 4.7mm",
"XL70E3 Enfield - 5.56mm",
"Gun Runners Service Rifle - 5.56mm",
"M16A2 - 7.62mm",
"Gun Runners Assault Rifle - 5mm",
"M4A1 - 5.56mm",
"Gun Runners Battle Rifle - .308",
"M1A1 Garand - .308",
"SVT-2055 - 7.62mm",
"Anti-Material Rifle - .50",
"DKS-501 - .223",
"DKS-302 - .308",
"M72 Gauss - SEC & 2mm EC",
"YCS/186 - SEC & 2mm EC",
"Wattz 2000 Laser Rifle - MFC",
"Van Graff Wattz 2000 Lazer Rifle - SEC",
"AER 9 Laser Rifle - MFC",
"AER 12 Laser Rifle - MFC",
"Van Graff AER 10 Laser Rife - MFC",
"Van Graff AER 9 Laser Rife - SEC",
"YK42B pulse rifle - MFC",
"Winchester P24 Plasma Rifle - MFC",

"Pump Action Grenade Launcher - 25mm",
"Over & Under Grenade Launcher - 40mm",
"Over & Under Grenade Launcher - 25mm",
"M38 Grenade Launcher - 20mm",
"M39 Grenade Launcher - 40mm",

"Lever Action - .44",
"Lever Action - .357"];

var falloutShotguns =["Double Barrel Shotgun - 20g",
"Over & Under Shotgun - 12g",
"Pump Action Shotgun - 12g",
"Gun Runner Pump Action Shotgun - 20g",
"Panchor Jackhammer - 12g",
"CAWS - 12g",
"Neostead Combat Shotgun - 12g",
"City-Killer Combat Shotgun - 12g",
"Single Barrel Shotgun - 12g",
"Single Barrel Shotgun - 20g",
"Riot Shotgun - 12g"];


var falloutBigguns =["Light Support Gun - .223",
"Bozar - .223",
"M60A3 - .762mm",
"Bozar - .223",
"Gun Runners Bozar - 7.62mm",
"CZ57 Minigun - 5mm",
"CZ53 Minigun - 5mm",
"BoS Avenger Minigun - 5mm",
"Vindicator Minigun - 4.7mm",
"Browning Machinegun - .50",
"M249 SAW - 5.56mm",
"Flamer - Fluid Tank",
"Rocket Launcher - Rockets",
"Shoulder Mounted MG - 10mm",
"Gun Runners Winchester P94 - MFC",
"Winchester P94 - MFC",

"Missile Laucher - Missile",
"Grenade Machinegun - 25mm"];

var falloutMelee = ["Shiv - Rusted",
"Knife - Utensil",
"Knife - Butcher",
"4x4 Board",
"4x4 Board - Nail1",
"Trench Shovel -Rusted",
"Pipe - Water",
"Baseball bat - Wooden",
"Baseball bat - Aliminum",
"Pole - Wooden",
"Pole - Metal",
"Shiv - Broken Edge",
"Cleaver",
"Cleaver - Jagged Blade",
"Combat Knife",
"Combat Knife - Super Carbon",
"Combat Knife - Saturnite",
"Machette - Blunt",
"Machette",
"Machette - Jagged Edge",
"Switch Blade - Decorated",
"Switch Blade",
"Shaving Razor",
"Straigth Razor",
"Hammer",
"Spiked Club",
"Baseball Bat - Wood",
"Baseball Bat - Metal",
"Hockey Stick - Reinforced",
"Hockey Stick - Metal",
"Hockey Stick - Wood",
"Sledge Hammer",
"Super Sledge - Broken hammerhead",
"Super Seldge - No Mechanism",
"Well Made Spear",
"Tribal Hunting Spear",
"Tribal Hunting Trident",
"Ripper - Missing Link",
"Ripper - Dulled",
"Ripper - No Motor",
"Knuckle Dusters",
"Knuckle Spiked",
"Claws",
"Hatchet",
"Wood Axe",
"Fire Axe - Wood",
"Fire Axe - Carbon",
"Katana",
"Katana - Replica",
"Cavalary Sword",
"Cavalary Sword - Reforged",
"Wakizashi",
"Golf Club",
"Baton"];

var falloutExplosives = ["Firecrackers",
"Box Of Firecrackers",
"Fireworks",
"Fireworks Bundle",
"Molotov Cocktail - Half Empty",
"Molotov Cocktail - Dried",
"Dynamite Stick",
"Dynamite Bundle",
"Fragmentation Grenade",
"Flashbang",
"Incendiary Grenade",
"Smoke Grendae",
"Plasma Grenade",
"Pulse Grenade",
"Potato Masher",
"Satchel Charge",

"Powder Charge",
"Bottlecap Mine",
"Fragmentation Mine",
"Hopper Mine",
"Plasma Mine",
"Pulse Mine",
"Tank Mine",
"Tribal Mine - Hallucination",
"Tribal Mine - Poison Mist",
"Tribal Mine - Snare Root",
"Anti-Tank Mine",
"Anti-PA Mine",
"Homemade Fertilizer Grenade",
"Homemade Fertilizer Mine",
"Homemade Fertilizer - Satchel"];



/* Weapon Conditions */
var firearmcondition = ["Jammed - Rusted",
"Jammed - Deformed Loading Mechanism",
"Jammed - Obstructed By Debris",
"Jammed - Dislocated Barrel",
"Rusted - Beyond Repair",
"Rusted - Salvage",
"Rusted - Fixable",
"Missing Part - Trigger",
"Missing Part - Shattered Barrel",
"Missing Part - Striker",
"Missing Part - Broken in half",
"Missing Part - Furniture & Body",
"Missing Part - Loading Mechanism",
"Missing Part - No Sights",
"Bent Barrel",
"Debris - Melted",
"Debris - Radioactive",
"Debris - Shattered Body",
"Debris - No Parts In Body",
"Servicable - Well Maintained",
"Servicable - Sealed In Plastic Bag",
"Servicable - Recently Fired",
"Dirty - Toxic Mud",
"Dirty - Radioactive Goo",
"Dirty",
"Well Worn",
"Good as new",
"Mint Condition",
"Mint Condition - Still in its case"];

var explosiveconditions = ["Bad Fuse",
"Corroded",
"Wet",
"Missing - Half",
"Missing - Broken Casing",
"Single",
"Ready to go",
"Mint",
"In Military Case",
"Armed",
"Ingredients - Missing Fuse",
"Ingredients - Including Recipe",
"Ingredients - Just Chemical Jars",
"Ingredients - Missing Casing",
"Military Crate"];

var meleeconditions = ["Rusted",
"Barely Together",
"Debris - Melted",
"Debris - Radioactive",
"Missing Part - Broken Handle",
"Missing Part - Broken In Half",
"Bent",
"Servicable",
"Dirty - Toxic Mud",
"Dirty - Radioactive Goo",
"Good Shape",
"Well Worn",
"Sturdy",
"Tribal - Improved",
"Tribal - Desecrated"];

var falloutMunitions = [".32",
"9mm",
"10mm",
".44",
".45",
".50 AE",
"Small Energy Cell",
"14mm",
".357",
"2mm EC",
"5mm",
"5.56mm",
"7.62mm",
"4.7mm",
".308",
".223",
"Microfusion Cell",
"25mm Frag Grenade",
"20mm Frag Grenade",
"40mm Frag Grenade",
".50"];

var munitionKind = ["Flechette",
"Full Metal Jacket",
"Hollow Point",
"Duplex Cartridge",
"Plastic Tip",
"Ballpoint",
"Crooked",
"Cracked Case"];