var falloutMedicine = ["Buffout",
"Mentats",
"Berry Mentats", 
"Orange Mentats", 
"Grape Mentats",
"Rad-X",
"RadAway",
"Stimpack",
"Super Stimpack",
"Ultra Stimpack",
"Healing Powder - Tribal",
"Healing Poultice",
"Healing Powder - Legion",
"Healing Powder - FoA",
"Hydra",
"Antidote",
"Pyscho",
"Pyscho - Mordino Pharma",
"Cateye",
"Fixer - Mordino Pharma",
"Fixer - FoA",
"Med-X",
"Med-X - Mordino Pharma",
"Slasher - Great Khans",
"Slasher - Mordino Pharma",
"Snakebite tourniquet"];

var falloutDrugs = ["Dixon's Jet",
"Jet",
"Ultra Jet",
"Rocket",
"Steady",
"Turbo",
"Afterburner Gum",
"Steady",
"Rebound",
"Rushing Water",
"Mutie"];

var falloutAlcohol = ["Gamma Gulp",
"Beer",
"Booze",
"Wine",
"Rot Gut",
"Roentgen rum",
"Scotch",
"Moonshine",
"Sierra Madre Martini",
"Vodka",
"Beer",
"Whiskey",
"Moonshine",
"Sunset Sarsaparilla - Tequila",
"Tequila",];

var chemConditions = ["Expired",
"Homebrew - Exceptional",
"Homebrew - Amateur",
"Homebrew - Caustic",
"Homebrew - Inbred Production",
"Professional - Selection",
"Professional - Mass Produce",
"Professional - Detestable",
"Concentrated",
"Foul",
"Watered down",
"Off brand",
"Radiated",
"Toxic",
"Poisonous",
"Rotten",
"Exposed"];