var falloutEncounterWild = ["Predator - Hunting",
"Predator - Nest",
"Predator - Wandering",
"Predator - Ambsuhing",
"Docile - Feeding",
"Docile - Lost",
"Docile - Resting",
"Docile - Set Loose",
"Gaint Ant - Nest",
"Gaint Ant - Hunting",
"Gaint Ant - Ambushing",
"Gaint/Bark Scorpion - Nest",
"Gaint/Bark Scorpion - Hunting",
"Gaint/Bark Scorpion - Ambushing",
"Wolf/Coyote/Dog - Hunting",
"Wolf/Coyote/Dog - Nest",
"Wolf/Coyote/Dog - Ambushing",
"Wolf/Coyote/Dog - Wandering",
"Sandshark - Hunting",
"Sandshark - Nest",
"Sandshark - Ambushing",
"Sandshark - Wandering",
"Mole Rat - Hunting",
"Mole Rat - Nest",
"Mole Rat - Ambushing",
"Mole Rat - Wandering",
"Yao Guai - Hunting",
"Yao Guai - Nest",
"Yao Guai - Ambushing",
"Yao Guai - Wandering",
"Tunneler - Hunting",
"Tunneler - Nest",
"Tunneler - Ambushing",
"Gecko - Wandering",
"Gecko - Hunting",
"Gecko - Nest",
"Gecko - Ambushing",
"Feral Ghoul - Trance",
"Feral Ghoul - Searching",
"Feral Ghoul - Agressive",

"Raider - Looting",
"Raider - Camping",
"Raider - Returning From Raid",
"Raider - Loitering",
"Raider - Exiled",
"Raider - Ambush",
"Raider - High as kite",
];

var falloutRaces =["Bark Scorpion",
"Radscorpion",
"Radroach",
"Cazador",
"Gaint Ant",
"Gaint Mantis",
"Bloatfly",
"Brahmin",
"Bighorner",
"Dog",
"Coyote",
"Wolf",
"Gaint Rat",
"Mole Rat",
"Radstag",
"Yao Guai",
"Gecko",
"Snake",
"Deathclaw",
"Tunneler",
"Ghoul",
"Mutant",
"Human",
"Feral Ghoul",
"Super Mutant"];

var falloutEncounterUrban =["Delirious Junkie",
"Muggers - Threatening",
"Muggers - Violent",
"Gang - Territory",
"Gang - Extortion",
"Gang - Intimidation",
"Crafstman",
"Mercenary with an interesting story.",
"Mercenary up for contract",
"Admirer",
"Hater",
"Agitated Youth",
"Protestors",
"Peddler",
"Crier - Merchant",
"Crier - Services",
"Crier - News",
"Newly arrived caravan",
"Departing caravan"];