var prostituteFNicknames = ["Semen Demon",
"Jizz Genie",
"Lovegoo Lass",
"Sperm Summoner",
"Ejaculate Empress",
"Mayonnaise Maiden",
"Jizz Jockey",
"Spunk Monk",
"Penile Perpetrator",
"Erection Confection",
"Boner Condoner",
"Fluid Druid",
"Wang Wizard",
"Prick Pirate",
"Dong Dominator",
"Sausage Sergeant",
"Pole Privateer",
"Shaft Specialist",
"Pecker Prodigy",
"Boner Benefactor",
"Tallywhacker Smacker",
"Man Muscle Steam Shovel",
"Willy Ghillie",
"Butt Hut",
"Glans Fans",
"Ejaculate Advocate",
"Wang Wrangler",
"Testicular Temptress ",
"Testicle Vestibule",
"Dick Duchess",
"Testicle Tamer",
"Cock Clairvoyant",
"Scrotum Totem",
"Prostate Magistrate"];

var prostituteMNicknames = ["Rock Rod",
"Solid Snake",
"Unbending Wood",
"Copulation Meister",
"Hard Reaction",
"Chamber Loader",
"Rod Stevard",
"Jack The Reaper",
"Full Loader",
"Stairway To Heaven",
"Soda Can",
"Ten Ton Hammer",
"Ever Ready Bunner",
"Cock of the Walk",
"Vinnie LaJoya",
"Sir Lance-a-lot",
"Dick Smothers",
"Jimmie Destroyer",
"Achtung! Dickzer",
"Longmember",
"Three Legs",
"Dave Handy",
"Plasma Caster",
"Cunning Linguist",
"Bulge Commander",
"Captain Orgasm",
"Twin Snakes",
"Unholy Hatless",
"Super Mutant"];

var doctorNicknames = ["Saw Bones",
"Medic",
"Doctor",
"Practioner",
"Butcher",
"Chop-Shop",
"Herbalist",
"Nurse",
"Homeopathist",
"Radiation Therapy",
"Dentist",
"Barber",
"Mortician",
"Professor",
"Medical Doctor",
"Fix-er Up-er",
"Shaman",
"Medicine man",
"Priest"];

var craftsmanNicknames = ["Sloppy",
"So so",
"Fraud",
"Amateur",
"Apperantice",
"Senior Apperantice",
"Master",
"Self-Thought",
"Expert",
"Renowned",
"Innovative",
"Best West Of Colorado",
"Genius"];

var gameRaces =["Radroach",
"Wild Brahmin",
"Wild Bighorner",
"Mole Rat",
"Radstag",
"Yao Guai",
"Gecko"];

var hunterWeapons =["Shotgonne - Breach Load .44",
"Lever Action - .50 AE",
"Hunting Rifle - .50 AE",
"Lever Action - .44",
"Lever Action - .357",
"Varmint Rifle - 5.56mm",
"Varmint Rifle - 7.62mm",
"DKS-501 - .223",
"Double Barrel Shotgun - 20g",
"Double Barrel Shotgun - 12g",
"Over & Under Shotgun - 12g",
"Pump Action Shotgun - 12g"];

var npcRaces =["human", "ghoul", "supermutant"];

var falloutCurrencies = ["Ringpull",
"Caps",
"NCR Dollar",
"Commonwealth Dolar",
"Mexican Dolar",
"Canada Dolar",
"Gold",
"Legion Coin",
"Teflon Munition",
"Fission Battery"];

var raiderTitles = ["Pyschopath",
"Man Eater",
"Delinquent",
"Petty Criminal",
"Bandit",
"Sociopath",
"Desperate",
"Junkie",
"Power Worshipper",
"Murderer",
"Animal",
"CLEM",
"Betrayer",
"Backstabber",
"Scourge",
"Pestilence",
"Degenerate",
"Did Absolutely Nothing Wrong",
"Demon Spawn",
"Human Garbage"];

var townTinykind = ["Hunter Rest",
"Caravan Camp",
"Traveller Rest",
"Raider Ambush"];

var caravanCompanies = ["Far Go Traders",
"Crimson Caravans",
"Happy Trails",
"Gun Runners",
"Far Go Traders",
"Mojave Express",
"NCR Supply Train",
"3-Some Caravan",
"Privately Owned",
"Self"];

var workshopState = ["Missing Necessary Tools",
"Missing Necessary Materials",
"Dirty",
"Partially Ruined",
"Neatly Organized",
"A Huge Mess",
"Miserable",
"Pristine",
"Well stocked"];

var structureMaterial = ["Log",
"Wooden",
"Plyboard",
"Metal Sheet",
"Sandcrete",
"Recyclerete",
"Concrete",
"Stone",
"Brick"];

var structureKind = ["Cabin",
"Hut",
"Ruin",
"Renovated Ruin",
"Apartment",
"Maison",
"Casa"];