var falloutDisease = ["New Plauge",
"Radiation Posioning",
"Troglodyte Degeneration Syndrome",
"Super Ebola",
"Parasitic Infection - Hyper Tape Worm",
"Parasitic Infection - Larval Infestation",
"Parasitic Infection - Fleas",
"Hyper AIDS",
"New Reno AIDS",
"Asthma",
"Influenza - Gecko",
"Influenza - Common",
"Influenza - Super",
"Influenza - Avian",
"Gonorrhea",
"New Reno Gonorrhea",
"Meningitis - Bacterial",
"Meningitis - Viral",
"Meningitis - Fungal",
"Hepatitis - Alcohol",
"Hepatitis - Viral",
"Hepatitis - X",
"Diarrhea - Poisioning",
"Diarrhea - Viral",
"Diarrhea - Cold",
"Alzheimer's Disease - Pyshic Trauma",
"Alzheimer's Disease - Age",
"Alzheimer's Disease - Diet",
"Blood Poisioning - Organic Compound",
"Blood Poisioning - Mineral",
"Blood Poisioning - Radiation",
"Jet - Addiction",
"Steady - Addiction",
"Afterburner Gum - Addiction",
"Steady - Addiction",
"Rebound - Addiction",
"Mutie - Addiction",
"Bubonic X Plague",
"Septicemic Plague",
"Pneumonia - Bacterial",
"Pneumonia - Viral",
"Pneumonia - Fungal",
"Mega Malaria",
"Raging Typhus",
"Depression - Clinical",
"Depression - Mild",
"Depression - Sucidial",
"Old World Blues - Mild Depression",
"Old World Blues - Chronic",
"Old World Blues - Sucidial",
"Post Traumatic Stress Disorder"];

var falloutDisability =["Deaf - Mild",
"Deaf - Left Ear",
"Deaf - Right Ear",
"Blind - Almost",
"Blind - Left Eye",
"Blind - Right Eye",
"Mute",
"Autistic - Obsessive",
"Autistic - Vegetable",
"Insane",
"Learning Disability",
"Dwarf",
"Dwarf - Mutated",
"Gigantism",
"Gigantism - Mutated",
"Missing/Crippled Left Leg",
"Missing/Crippled Right Leg",
"Missing/Crippled Left Arm",
"Missing/Crippled Right Arm",
"Missing/Crippled Left Hand",
"Missing/Crippled Right Hand",
"Missing/Crippled Left Foot",
"Missing/Crippled Right Foot",
"Missing/Crippled Left Eye",
"Missing/Crippled Right Eye",
"Missing/Crippled Left Ear",
"Missing/Crippled Right Ear",
"Paralysis - Upper Body",
"Paralysis - Lower Body",
"Paralysis - Vegetable"];

var falloutPerson =["Survivor",
"Survivalist - Selfcentered",
"Survivalist - Loner",
"Survivalist - Mercenary",
"Survivalist - Agressive",
"Survivalist - Hopeless",
"Survivalist - Adventurer",
"Farmer - Settled",
"Farmer - Helping Hand",
"Farmer - Desperate",
"Farmer - Landed",
"Farmer - Happy",
"Craftsman - Mecahnics",
"Craftsman - Toolsmith",
"Craftsman - Weaponsmith",
"Craftsman - Construction",
"Craftsman - Cook",
"Craftsman - Merchantile",
"Craftsman - Chemicals",
"Craftsman - Clothmaker",
"Craftsman - Mechanic",
"Caravaneer - Mail",
"Caravaneer - Explorer",
"Caravaneer - Trader",
"Caravaneer - Cargo Train",
"Caravaneer - Contractor",
"Mercenary - Caravan Guard",
"Mercenary - Town Milita",
"Mercenary - Freelancer",
"Mercenary - Unemployed/Mysterious",
"Mercenary - Retired",
"Mercenary - Adventurer",
"Tribal - Savage",
"Tribal - Isolated",
"Tribal - Refugee",
"Tribal - Native",
"Tribal - Envoy",
"Tribal - Vault Origin",
"Junkie - Organized Raider",
"Junkie - Unorganized Raider",
"Junkie - Baked",
"Junkie - Agressive",
"Junkie - Dying Slowly",
"Dealer - Rich",
"Dealer - Secretive",
"Dealer - Junkie",
"Dealer - Exceptional Stock",
"Hunter - Trapper",
"Hunter - Big Game Hunter",
"Hunter - Retired/Trader",
"Local Militia - Adventurer",
"Local Militia - Stuck up",
"Local Militia - Abusive",
"Local Militia - Bored",
"Peasant - Hard Working",
"Peasant - Rebellious",
"Peasant - Sad",
"Peasnat - Physical Work",
"Urban Citizen - Lost Tourist",
"Urban Citizen - Holier Then Thou",
"Urban Citizen - Political Activist",
"Urban Citizen - Victim",
"Urban Citizen - Business",
"Urban Citizen - NCR Government",
"Urban Citizen - Shi Tourist",
"Urban Citizen - Vault Origin",
"Urban Citizen - Tribal Origin",
"Merchant - Weapons & Ammo",
"Merchant - Industrial",
"Merchant - Leather Works",
"Merchant - Jewelry & Precious Metals",
"Merchant - Household",
"Merchant - Construction",
"Merchant - Farming Equipment",
"Merchant - Medical Equipment",
"Merchant - Armor",
"Merchant - Electronics",
"Merchant - Foodstuff",
"Merchant - Alcoholic",
"Merchant - Pharmacology",
"Entertainer - Musician",
"Entertainer - Acrobat",
"Entertainer - Comedian",
"Entertainer - Singer",
"Entertainer - Trickshooter",
"Entertainer - Storyteller",
"Genius - Science!",
"Genius - Mechanics!",
"Genius - Cloth/Armor!",
"Genius - Tactics!",
"Genius - Survival Skills!",
"Genius - Biology!",
"Business - Bartender",
"Business - Workshop",
"Business - Kitchen/Distillery",
"Business - Human Resources",
"Business - Druugs",
"Business - Farm/Chemicals",
"Business - Computer Repair",
"Business - Holodisk Player Repair"];