var falloutPipAdds = ["",
""];

var falloutTools =["Hair Pin",
"Electronic Lockpick I",
"Electronic Lockpick II",
"Lockpick Set",
"Expended Lockpick Set",
"Safe-Openator 4000 - Single Use",
"Safe-Openator 4000 - Rechargable",
"Lubrica 10000 - Multipurpose Oil",
"Shovel",
"Pickaxe",
"Hoe",
"Kitchen Utensil",
"Fusion Reactor Seal",
"Electrician Tools",
"Swiss Army Knife",
"Multi-Tool",
"Tool Set - Bandolier",
"Tool Kit",
"Super Tool Kit",
"First Aid Kit - Satchel",
"Doctors Bag - Legion",
"Doctors Bag",
"Paramedic Kit - Backpack",
"Paramedic Kit - Bag",
"Weapon Care pack",
"Weapon Repair Toolkit",
"Food sanitizer",
"Gieger Counter"];

var falloutReading =["Big Book Of Science",
"Dean's Electronics",
"First Aid Book",
"Guns and Bullets",
"Scout Handbook",
"Crimson Caravan: Employee Handbook",
"Nikola Tesla And You!",
"Duck and Cover",
"Tumblers Today",
"D.C. Journal Of Medicine",
"Lying, Congressional Style",
"Wasteland Survival Guide",
"Pugilism Illustrated",
"Boxing Times",
"Fixin' Things",
"Future Weapons Today",
"Lad's Life",
"¡La Fantoma!",
"Locksmith's Reader",
"Meeting People",
"Milsurp Review",
"Patriot's Cookbook",
"Programmer's Digest",
"Salesman Weekly",
"Tæles of Chivalrie",
"Today's Physician",
"True Police Stories",
"Astoundingly Awesome Tales",
"Grognak the Barbarian",
"Live & Love",
"U.S. Covert Operations Manual",
"Hot Rodder",
"La Coiffe",
"Picket Fences",
"RobCo Fun",
"Taboo Tattoos",
"Total Hack",
"Cats Paw"];

var readingConditions =["In Mexican Language",
"In Canadian Language",
"Wet - Sticky Pages",
"Wet - Melded Pages",
"Wet - Glowing Fungi",
"Wet - Mushy",
"Burnt - Half Readable",
"Burnt - Only Cover Left",
"Well Worn - Ripped Pages",
"Well Worn - With Marked Pages",
"Pristine - Reprint",
"Pristine - Annoted Reprint",
"Well Preserved"];


var toolConditions =["Missing Items",
"Bent",
"Broken",
"Pristine",
"Rusted - Repairable",
"Rusted - Beyond Repair",
"Empty",
"Dirty - Toxic Mud",
"Dirty - Radioactive Goo",
"Well Worn",
"Sturdy",
"Debris - Melted",
"Debris - Radioactive",
"Well Worn",
"Good as new",
"Mint Condition",
"Mint Condition - Still in its case"];