var falloutDisease = ["New Plauge",
"Radiation Posioning",
"Troglodyte Degeneration Syndrome",
"Super Ebola",
"Parasitic Infection (Hyperactive Tape Worm)",
"Parasitic Infection (Larval Infestation)",
"Parasitic Infection (ADHD Fleas)",
"Hyper AIDS",
"New Reno AIDS",
"Asthma",
"Influenza (Gecko)",
"Influenza (Common)",
"Influenza (Super)",
"Influenza (Avian)",
"Gonorrhea",
"New Reno Gonorrhea",
"Meningitis (Bacterial)",
"Meningitis (Viral)",
"Meningitis (Fungal)",
"Hepatitis (Alcohol)",
"Hepatitis (Viral)",
"Hepatitis (X)",
"Diarrhea (Poisioning)",
"Diarrhea (Viral)",
"Diarrhea (Cold)",
"Alzheimer's Disease (Pyshic Trauma)",
"Alzheimer's Disease (Age)",
"Alzheimer's Disease (Diet)",
"Blood Poisioning (Organic Compound)",
"Blood Poisioning (Metal)",
"Blood Poisioning (Radiation)",
"Jet Addiction",
"Steady Addiction",
"Afterburner Gum Addiction",
"Rebound Addiction",
"Mutie Addiction",
"Bubonic X Plague",
"Septicemic Plague",
"Pneumonia (Bacterial)",
"Pneumonia (Viral)",
"Pneumonia (Fungal)",
"Mega Malaria",
"Raging Typhus",
"Depression (Clinical)",
"Depression (Mild)",
"Depression (Sucidial)",
"Old World Blues (Mild Depression)",
"Old World Blues (Chronic)",
"Old World Blues (Sucidial)",
"Post Traumatic Stress Disorder"];

var falloutDisability =["Mild Deafness",
"Deafness in Left Ear",
"Deafness in Right Ear",
"Almost Blind",
"Blind Left Eye",
"Blind Right Eye",
"Muteness",
"Autism",
"Insanity",
"Learning Disability",
"Dwarfism",
"Mutated Dwarfism",
"Gigantism",
"Mutated Gigantism",
"Crippled Left Leg",
"Crippled Right Leg",
"Crippled Left Arm",
"Crippled Right Arm",
"Crippled Left Hand",
"Crippled Right Hand",
"Crippled Left Foot",
"Crippled Right Foot",
"Crippled Left Eye",
"Crippled Right Eye",
"Crippled Left Ear",
"Crippled Right Ear",
"Missing Left Leg",
"Missing Right Leg",
"Missing Left Arm",
"Missing Right Arm",
"Missing Left Hand",
"Missing Right Hand",
"Missing Left Foot",
"Missing Right Foot",
"Missing Left Eye",
"Missing Right Eye",
"Missing Left Ear",
"Missing Right Ear",
"Paralysis (Upper Body)",
"Paralysis (Lower Body)",
"Paralysis (Vegetable)"];

var falloutPerson =["Survivor",
"Survivalist (Selfcentered)",
"Survivalist (Loner)",
"Survivalist (Mercenary)",
"Survivalist (Agressive)",
"Survivalist (Hopeless)",
"Survivalist (Adventurer)",
"Farmer (Settled)",
"Farmer (Helping Hand)",
"Farmer (Desperate)",
"Farmer (Landed)",
"Farmer (Happy)",
"Craftsman (Mecahnics)",
"Craftsman (Toolsmith)",
"Craftsman (Weaponsmith)",
"Craftsman (Construction)",
"Craftsman (Cook)",
"Craftsman (Merchantile)",
"Craftsman (Chemicals)",
"Craftsman (Clothmaker)",
"Craftsman (Mechanic)",
"Caravaneer (Mail)",
"Caravaneer (Explorer)",
"Caravaneer (Trader)",
"Caravaneer (Cargo Train)",
"Caravaneer (Contractor)",
"Mercenary (Caravan Guard)",
"Mercenary (Town Milita)",
"Mercenary (Freelancer)",
"Mercenary (Unemployed/Mysterious)",
"Mercenary (Retired)",
"Mercenary (Adventurer)",
"Tribal (Savage)",
"Tribal (Isolated)",
"Tribal (Refugee)",
"Tribal (Native)",
"Tribal (Envoy)",
"Tribal (Vault Origin)",
"Junkie (Organized Raider)",
"Junkie (Unorganized Raider)",
"Junkie (Baked)",
"Junkie (Agressive)",
"Junkie (Dying Slowly)",
"Dealer (Rich)",
"Dealer (Secretive)",
"Dealer (Junkie)",
"Dealer (Exceptional Stock)",
"Hunter (Trapper)",
"Hunter (Big Game Hunter)",
"Hunter (Retired/Trader)",
"Local Militia (Adventurer)",
"Local Militia (Stuck up)",
"Local Militia (Abusive)",
"Local Militia (Bored)",
"Peasant (Hard Working)",
"Peasant (Rebellious)",
"Peasant (Sad)",
"Peasnat (Physical Labour)",
"Urban Citizen (Lost Tourist)",
"Urban Citizen (Holier Then Thou)",
"Urban Citizen (Political Activist)",
"Urban Citizen (Victim)",
"Urban Citizen (Business)",
"Urban Citizen (NCR Government)",
"Urban Citizen (Shi Tourist)",
"Urban Citizen (Vault Origin)",
"Urban Citizen (Tribal Origin)",
"Merchant (Weapons & Ammo)",
"Merchant (Industrial)",
"Merchant (Leather Works)",
"Merchant (Jewelry & Precious Metals)",
"Merchant (Household)",
"Merchant (Construction)",
"Merchant (Farming Equipment)",
"Merchant (Medical Equipment)",
"Merchant (Armor)",
"Merchant (Electronics)",
"Merchant (Foodstuff)",
"Merchant (Alcoholic)",
"Merchant (Pharmacology)",
"Entertainer (Musician)",
"Entertainer (Acrobat)",
"Entertainer (Comedian)",
"Entertainer (Singer)",
"Entertainer (Trickshooter)",
"Entertainer (Storyteller)",
"Traveller (Merchant)",
"Traveller (Caravan)",
"Traveller (Mercenary)",
"Traveller (On Quest)",
"Traveller (On Mission)",
"Traveller (Business)",
"Traveller (Lost)",
"Tribal (Foraging)",
"Tribal (Camping)",
"Tribal (Hunting)",
"Tribal (Exiled)",
"Tribal (Ambush)",
"Tribal (Merchant)",
"Tribal (On Quest)",
"Tribal (Trance)",
"Tribal (Physical Labour)",
"Genius (Science!)",
"Genius (Mechanics!)",
"Genius (Cloth/Armor!)",
"Genius (Tactics!)",
"Genius (Survival Skills!)",
"Genius (Biology!)",
"Business (Bartender)",
"Business (Workshop)",
"Business (Kitchen)",
"Business (Human Resources)",
"Business (Chemicals)",
"Business (Farm)",
"Business (Computer Repair)",
"Business (Holodisk Player Repair)"];