//http://www.traykon.com/extras/ Copywrite 1999 Dawn Ibach
var npcQuirks =[
"Scar",
"Monocle ",
"Gaps between teeth",
"Rash",
"Tattoo",
"Missing limb",
"Missing Joints",
"Missing Fingers",
"Missing teeth",
"Spits when talking",
"Fidgets ",
"Picks ears",
"Rubs hands together ",
"Sucks on teeth",
"Mismatched eyes ",
"Acne",
"Overweight",
"Underweight ",
"Always eating or drinking ",
"Bites fingernails ",
"Wandering eye ",
"Facial piercing ",
"Limp",
"Lisp",
"Foreign clothing",
"Accent",
"Uses long words incorrectly ",
"Rubs chin ",
"Tugs on ear ",
"Picks nose",
"Bites lower lip ",
"Trims or cleans nails with long knife ",
"Twirls hair with finger ",
"Single hair or beard braid",
"Many hair or beard braids ",
"Rings or bells in hair or beard braids",
"Smells like sweat ",
"Smells like dogs",
"Smells like horses",
"Smells like cheap cologne ",
"Smells like expensive cologne ",
"Smells like cedar wood",
"Smells like tobacco ",
"Smells like lavender",
"Smells like alcohol ",
"Smells like soap",
"Smells like roses ",
"Scratches ",
"Has leaves in hair or clothing",
"Wears flower in hair or clothing",
"Squints ",
"Sniffs often",
"Braggart",
"Never looks anyone in the eye ",
"Superstitious ",
"Unusual jewelry ",
"Freckles",
"Pockmarked skin ",
"Eye tic ",
"Bucktoothed ",
"Talks loudly",
"Whispers",
"Holier than thou attitude ",
"Makes puns",
"Clumsy",
"Quotes famous poet, regularly ",
"Quotes religious text ",
"Refers to self in third person",
"Chews grass, stick, or leaves ",
"Closely examines everything ",
"Keeps hand on weapon",
"Keeps hands in pockets",
"Hairless",
"Exotic weapon ",
"Claps hands often ",
"Smacks palm with fist ",
"Asks often about his own appearance ",
"Rubs palms on thighs",
"Stretches often ",
"Seems cold or hot ",
"Yawns often ",
"Polishes brooch or buckle often ",
"Rubs luckstone or fetish",
"Twirls coin between fingers ",
"Always wears thick, leather gloves",
"High squeaky voice",
"Offers exotic beverages or foods",
"Oily skin or hair ",
"Obvious cosmetics ",
"Lazy eye",
"Always wears ‘lucky’ hat, scarf, ring ",
"Mole",
"Always wears favorite color ",
"Wears clothes too big or too small",
"Wears obvious wig ",
"Uses a parasol",
"Picks teeth with knife or fingernails ",
"Waxed facial hair ",
"Belches loud and often",
"Sneezes often ",
"Coughs regularly",
"Blinks often",
"Wine colored birthmark",
"Rubs eyes often ",
"Chews on braid or lock of hair",
"Bites fingernails or cuticles ",
"Polishes spectacles, never wears them ",
"Twists ring ",
"Picks lint off clothes, his and PCs ",
"Has hiccups ",
"Watering eye(s) ",
"Taps foot or drums fingers",
"Sunburn and peeling skin",
"Dark tan",
"Very pale ",
"Toothless ",
"Dressed in furs or leather",
"Dressed in formal attire",
"Dressed in silks and lace ",
"Has black eye ",
"Bruised extremities ",
"Arm in sling",
"Bandaged extremity",
"Stutters",
"Tongue tied ",
"Mixes languages ",
"Mixes gibberish with words",
"Keeps arms folded ",
"Picks at scabs or loose skin",
"Dresses colorblind",
"Has wart on hand, covers it always",
"Hand covers mouth while speaking",
"Keeps hand on PCs shoulder",
"Carries crumbs to feed birds",
"Hands coppers to beggar children",
"Speaks to animals like people ",
"Speaks to ‘spirits’ ",
"Has paint stained hands and clothes ",
"Wears scarf around ankles or wrists ",
"Wears vest with bell buttons",
"Fascinated by fire",
"Fascinated by non human races ",
"Clothes have bulging pouches",
"Archaic speech",
"Spotless, glossy boots",
"Rope burns around neck or wrists",
"Pasted on moustache or beard",
"Hair dye covering collar",
"Writes down everything PC says",
"Wears armor covered in runes",
"Has vampire bite scars on neck",
"Has arthritis in hands",
"Rubs old knee injury",
"Avoids crowds ",
"Nose bleeds ",
"Wears notched belt",
"Wears well tended ancient weapon",
"Refers to good old days often ",
"Wears heart shaped beauty mark",
"Has one or more gold teeth",
"Ogles opposite sex openly ",
"Paper cuts and ink stained fingers",
"Serious burn scar ",
"Rings sewn on clothes with fetishes ",
"Clothes made of woven leaves",
"Pregnant woman",
"Rubs calluses on palms with thumb ",
"Carries cloth covered basket",
"Sharpens knife with whetstone ",
"Spit polishes thick, fancy bracelet ",
"Hard of hearing ",
"Gives a different name every meeting",
"Regularly blows stray hair out of eyes",
"Bows before speaking and after",
"Flatulent ",
"Hooks thumbs in belt and bounces",
"Walks like a sailor ",
"Crumbs in beard and clothes ",
"Food stained face ",
"Wine stained ‘moustache’",
"Carries small snake, mouse, or lizard ",
"Wears foreign style clothes ",
"Has long, lacquered nails ",
"Mute, speaks through sign language",
"Blind, sees through familiar’s eyes ",
"Uses foul language",
"Runny nose",
"Always late ",
"Instructs PCs on latest fashion ",
"Bad cook, begs PCs to eat ",
"Rubs large belly often",
"Blatantly pouts ",
"Calls PCs by wrong names",
"Convinced PCs need reforming",
"Giggles, inappropriately",
"Wears ancient fashions",
"Combs hair with fingers ",
"Jingles coins in pocket or pouch",
"Intoxicated or acting ",
"Talks in rhyme",
"Plays with charm on necklace",
"Says “hmm – hmm” often",
"Asks rhetorical questions and answers ",
"Denies gossiping and proceeds to gossip ",
"Falsely claims he is an adventurer too",
"Greatly exaggerates ",
"Nods often",
"Gestures wildly with hands",
"Carries satchel filled with junk",
"Hacking cough ",
"Sweats profusely",
"Shaving cuts on face",
"Military manner ",
"Animal bite or claw scar",
"Sleepy",
"Always out of breath",
"Sketches PC while talking ",
"Flips key ring with finger",
"Covered with road dust",
"Rolls “R’s” while speaking",
"Snorts while laughing ",
"Complains of heartburn",
"Talks of health problems",
"Loses items and asks PCs to help look ",
"Survived torture, has no fingernails",
"Vegetarian",
"Only eats meat",
"Conceited ",
"Pathological liar ",
"Taps foot incessantly ",
"Rubs back of neck "];

