/* RANDOM ITEM TABLES BY: The ONE, the ONLY- ¡L! ¡D! ¡MCFEAR! This is a collection of 8 (currently) random item tables meant MOSTLY for RIFTS: Earth. Item Tables 1 through 8 the Humourous Encounter Table were written by LDMCFEAR (I only edited for spelling and such). */
var trashlist = ["Small bottle — excellent condition, contains super-strength bonding glue, poison if ingested.",
"Plastic box — good condition, holds modeling clay.",
"Small bottle — fair condition, contains turpentine.",
"Toy — fair condition, yo-yo, string missing.",
"Hockey puck — perfect condition.",
"Aluminum cylinder — good condition (baseball bat).",
"Metal loops — excellent condition (handcuffs, open, but without key).",
"Sheath knife — fair condition, point broken.",
"Metal file — good condition.",
"Plastic box — good condition, contains small tubes and spheres, (Fireworks), 10-100 total.",
"Plastic bottle of liquid — good condition (paint of miscellaneous color).",
"Hand air pump — excellent condition, metal cylinder with plastic hose and brass fittings.",
"Opaque plastic bag — fair condition, contains various sizes of rubber bands.",
"Plastic tubing — good condition, two centimeter diameter, 20m in length.",
"Plastic box — fair condition, contains 10 unpainted lead figurines in good condition.",
"Power tool — fair condition, battery powered drill (no battery), 2-12 bits in the handle compartment.",
"Hardware — excellent condition, can opener.",
"Plastic box — fair condition, 20-80 plastic pieces inside (scale model building toy).",
"Plastic cording — good condition, electrical extension cord with plug, 15 meters long.",
"Metal rod — excellent condition, ceramic base, wire attachment (lightning rod).",
"Metal helmet — good condition, no liner or strap.",
"Metal lug wrench — fair condition, somewhat corroded.",
"Plastic disc, large — poor condition, melted child’s toy.",
"Plastic bottle — excellent condition, contains man’s deodorant.",
"Small sack — excellent condition, is packed with thick white powder (plaster of Paris).",
"Metal frame — poor condition, twisted and dented picture frame.",
"Metal chain — fair condition, dog collar.",
"Metal trap — good condition, bear trap.",
"Small metal device — poor condition, pencil sharpener (broken).",
"Metal loop — good condition, basketball hoop.",
"Ceramic pot — fair condition, flower vase.",
"Plastic container — excellent condition, no label, contains room deodorizer which now has turned into in a poison gas covering a 5 meter area upon opening.",
"Plastic container — good condition, holds white powder (rat poison).",
"Metal can — perfect condition, contains sugared honey.",
"Metal can — good condition, contains heavy grease.",
"Metal can — excellent condition, contains assorted hard candy.",
"Metal can — fair condition, contains salted nuts in rancid oil.",
"Metal can — good condition, contains a joke “snake” that springs out when opened.",
"Metal can — fair condition, contents turned to powder that gives off radiation.",
"Metal can — good condition, contains military issue protein powder sufficient to feed eight people for three days if mixed with water.",
"Plastic ring, large — good condition, hula hoop toy.",
"Plastic strip — excellent condition, boomerang.",
"Claw Hammer — good condition, but handle broken",
"Plastic coat hanger — poor condition (partially melted)",
"Nylon Rope — good condition (20m coil)",
"Entrenching tool — fair condition, rusted",
"Bicycle reflector — good condition (red, yellow, white, or blue color)",
"Pencil — excellent condition, point broken",
"8 Small bottle of insect repellent — fair condition",
" .22 cal pistol — fair condition, 9 shot capacity",
"Home doughnut maker — poor condition",
"News magazine or comic book — very poor condition",
"Plastic bag of grass seed — fair condition",
"Screwdriver — fair condition",
"Ceramic salt shaker — good condition, full",
"Bicycle — fair condition, seat missing and tires flat",
"Stapler — poor condition, no staples",
"Plastic container — excellent condition, full of plant food",
"2-12 aluminum arrows — fair condition, feathers gone",
"Book — good condition, reading primer",
"Pair of scissors — fair condition, screw rusted",
"Plastic box — excellent condition, contains a complete set of 60 Chinese checkers marbles",
"Crash helmet with visor — fair condition, strap missing",
"Board game — poor condition, pieces missing, cards torn, board stained",
"Book — fair condition, SF novel, cover and last page missing",
"Small shaker — good condition, full of red pepper",
"Hacksaw — good condition, blade has plastic guard",
"Small container — fair condition, contains herbs or spices (pick one at random)",
"Plastic box — fair condition, holds 50-100 screws of assorted types and sizes",
"Electric knife sharpener — good condition but cord missing",
"Case of 150 12 gauge shotgun shells (deer slugs/ buck shot/ bird shot) — poor condition",
"Large metal shears — fair condition",
"Portable hand vacuum cleaner — condition appears excellent but motor is missing",
"Pair of water skis — perfect condition",
"Adjustable wrench — fair condition, adjusting screw corroded",
"Large plastic box — excellent condition, contains a hang glider kit",
"Small plastic bottle of colored liquid — good condition, contains colored dye",
"Magnifying glass — excellent condition, but several chips around edges",
"Small plastic box — perfect condition",
"Eight-track tape — fair condition, Black Sabath",
"Book — fair condition, dictionary",
"Smoke detector— poor condition, batteries missing",
"Plastic table knife — perfect condition",
"Book — good condition, western novel with cover missing",
"car hubcap — good condition, but dented",
"Plastic baseball — perfect condition",
"1 -6 empty soft drink bottles — good condition",
"Book — fair condition, any one volume of an encyclopedia",
"License plate — poor condition",
"Plastic box — good condition, holds 50-100 assorted nails",
"Plastic garden hose — fair condition, 5-20m",
"Nylon fishing line — excellent condition, 50m length",
"Vinyl patching kit — good condition, 6 patches",
"Doorknob and shank — perfect condition",
"Garbage can — poor condition, badly rusted and hole ridden",
"Toy laser pistol — perfect condition, battery missing (buzzes and flashes when working)",
"Cosmetic item, women’s — fair condition, mascara bottle",
"Metal cooking utensil — poor condition, tea kettle",
"Metal can — good condition, contains oil (penetrating/ lubricating/cooking)",
"Metal pipe — excellent condition (household water pipe 1-4m in length)",
"Plastic box — fair condition, designed to hold facial/toilet paper or napkins",
"Telephone, push button model — excellent condition",
"World globe — fair condition, badly outdated",
"Stainless steel spoon — good condition, handle bent",
"Pliers/wire cutters — fair condition",
"Set of colored pencils — poor condition, leads broken",
"Bottle — perfect condition, no label, contains vinegar",
"Plastic box — excellent condition, contains 50 different multi-colored children’s blocks made of lightweight plastic",
"Bottle — good condition, no label, contains 100-proof Scotch whisky",
"Flashlight — fair condition, no batteries",
"Plastic box — fair condition, contains 50-100 assorted nuts, bolts, and washers",
"Toiletry article — fair condition, man’s razor (no blades)",
"Screwdriver — good condition, Phillips head",
"Book — poor condition, telephone directory",
"Book — fair condition, gothic horror",
"Plastic dinnerware, 1-4 pieces — fair condition, partially melted",
"1-100 rounds of .22 cal, rifle ammunition — good condition",
"Leather bag — fair condition, holds 3-18 plastic polyhedra objects (dice) in good condition",
"Book — good condition, small arms instruction manual",
"Crate full of boots",
"Box of 48 crayons",
"Two folding chairs",
"Survival knife",
"Full harness for random type of mount",
"Can of Black Spray Paint (Krylon)",
"Box full of plastic Plants",
"Swiss army knife",
"One box of Heavy-duty plastic garbage bags",
"12 strings of blinking Xmas lights",
"Five huge fur skins (blanket size)",
"10 lbs. Of common 12 penny nails",
"Six thick rubber straps (60 cm long)",
"Compound bow & 12 steel shaft arrows",
"Mountain climbing gear (200 meter rope, spikes, clips, etc )",
"Bullhorn with re-chargeable battery",
"Portable, hand cranked electric generator",
"Large brass birdcage",
"Two dozen plastic containers of various sizes (Tupperware)",
"Three pairs of Oakly sunglasses (Blades)",
"Case of handcuffs (25 pairs with keys)",
"Plastic bag with three old comics inside",
"Workman’s vest with multiple pockets, straps and holsters for tools",
"Four Rubberized ponchos with hoods",
"300 meters of nylon fishing line",
"Small steel hanging weight scale",
"Six 81mm high explosive mortar shells",
"World war II hand cranked air raid siren",
"Rifts Sourcebook I (Rare out of print Edition)",
"Crank can opener / bottle opener",
"Barding for one random type mount",
"24 meters of stainless steel chain",
"One case of wine ( Six of the twelve bottles are poisoness now)",
"Nine 81mm White Phosphorus mortar rounds",
"Two cans of insect repellent",
"Three one-gallon plastic collapsible water jugs",
"One months worth of dried rations (MRE’s eat at own risk)",
"12 81mm parachute flare mortar rounds",
"Three saddles random type",
"13 shiny steel 6 inch disks",
"One tube of toothpaste (Aquafresh)",
"Toolbox with complete toolset",
"Two toy plastic shields",
"Leopould 20x40 rifle scope still in box new",
"Seven Glow in the dark Frisbees",
"Foot operated sewing machine (large and heavy)",
"A one meter long Crowbar (ala Half-Life)",
"Motion tracker (from the movie Aliens / Movie prop)",
"Tent sized mosquito netting",
"Spray on water repellant (100 square feet)", 	
"Three meter diameter collapsible umbrella",
"One crate of 200 oiled steel ball bearings",
"Silent dog whistle",
"One carefully packed set of six crystal goblets",
"Kevlar helmet",
"Folding, super-sharp tree saw",
"Insulated industrial asbestos gloves",
"Folding trench Shovel",
"One case of toilet paper (with Osama Bin-Ladens face on each sheet)",
"25 meters of black electrical tape",
"Movie - 12 Monkeys on DVD",
"World War II steel Nazi helmet",
"Sling Shot (Wrist Rocket brand)",
"30 meters of silver electrical cable",
"Plastic football helmet (logo warn off)",
"Attachable universal pistol stock",
"Box of miscellaneous jewelry",
"Trunk full of musical instruments",
"Complete human sized wardrobe",
"Intricate music box (broken)",
"A complete set of steel files",
"Three sheets of 4” foam rubber (4’ x 8’ each)",
"A large book of military history and tactics",
"Three-gallon pump sprayer (for insecticide)",
"Two human sized all-weather sleeping bags",
"Four circular saw blades",
"Old set of Starlight goggles (need batteries)",
"Metal briefcase with keys for lock",
"Range finder (cracked lens)",
"A sealed gallon of chocolate syrup",
"A Box of 30 meters of Aluminum foil",
"Staple gun with 400 staples",
"Set of five craft books (basket-weaving, knitting, etc)",
"One box of plastic Band-aids",
"Set of Photos (10 black and whites of New York city before the Holocaust)",
"Box of twelve No. 2 pencils",
"Hearing aid with permanent battery",
"Cookbook for campers (enough illustration to allow illiterates to understand and use it)",
"World War II aviator’s uniform",
"One Remington model 700 .308 caliber rifle new in box",
"One quart can of Brass-O metal polish",
"Box of 24 candles, complete with matches",
"Three empty metal liquor Flasks",
"10 Broken E-clips",
"Two Broken Sony car stereos",
"One complete diving outfit (scuba gear and an anti-shark suit that acts as fine-mesh chain mail, plus a speargun)",
"Sealed battery Stopwatch",
"Miners helmet with lamp",
"Manual on electrical wiring",
"Complete Motorcycle in mint condition (built by Orange County Choppers)",
"Collection of U.S. Military unit badges (23 misc. badges GM’s Discretion)",
"Box of eight coloring books, each about a different popular cartoon character",
"A Folding table (with one bent leg)",
"Box of 12 magnesium flares (one flare burns for ten minutes)",
"Tarnished Brass Knuckles",
"Mini-DVD computer game Fallout 4",
"Box Full of Hard Soap Bars",
"Mini-DVD player with assorted Movies and musical disks (7 disks total) needs bateries",
"One box of plastic wrap (30 meters)",
"A larger Aluminum Christmas tree",
"One five-person inflatable raft (missing oars)",
"A sledge hammer",
"A coil of high tensile strength wire (25 meters)",
"Rubberized plastic hammock",
"Five rolls of plastic packing tape (each roll contains 20 meters)",
"Three Pip-Boy 2000 Personal Data Assistants with sealed permanent batteries (use mini-DVD’s)",
"Ancient portable hand cranked record player",
"80-liter glass aquarium with air pump and filter (filter dirty and the pump in broke)",
"A metal pressure cooker (rusted)",
"One Velvis painting, An image of a singer, obviously, very old. The image has a felt coating that is still in good condition. It weighs 12 pounds",
"package of Firecrackers (sealed in plastic wrap)",
"A Buyers guide of old coins (published in the late 21st century)",
"Strap on metal spurs (wearing them allows a character to climb a tree, or wooden pole like the cable guy)",
"Four 5-meter-square fishing nets",
"An empty reel capable of holding 300 meters of nylon line",
"Small steel wire cutters (chipped edges)",
"Tazer (delivers 500,000 volts, at a range of 10 meters)",
"World war II map of America; Shows Alaska and Hawaii as “territories” not states",
"Lexicon of the German Language Published Circa 1932 (English Translation)",
"Six Long-handled, metal, campfire forks",
"Four (intact) Philips everlasting LED Light bulbs",
"One chain cutter",
"Five rubber-band wind up balsa wood model airplanes (flies 10 meters)",
"Blow gun (5 darts)",
"A collapsible, two-burner, camping stove (operates on Ethanol, is currently empty)",
"Four liters of Ethanol; If you drink it, it won’t ‘kill’ you, but you may wish it had afterwards",
"Twelve miniature microphones (bugs) – (sealed batteries, operates at a 200 meter distance)",
"1000 meters of coiled nylon rope (550 cord aka “Parachute cord”)",
"Two decks of bicycle brand playing cards (still sealed in box)",
"Copy of Aliens Vs. Predator the movie platinum edition on Mini-DVD (new in box)",
"A book on card games",
"One Everlasting Philips Blue-LED flashlight. Missing batteries)",
"One Dozen standard E-clips (six are fully charged, four are half charged, one is empty, one is cracked and will explode if re-charged)",
"E-clip re-charger (pre-rifts design)",
"two pairs of ever-sharp scissors",
"One set of Ginsue Steak Knives (Blades are dull)",
"Bio Med Gel. A jar of Bio Gel used in the biomedical field", 
"A plastic tarp (7×7 meters)",
"Two cans of fluorescent yellow (krylon) spray paint",
"Cat’s Paw Issue #5. This is the hard to find Issue 5 of Cat’s Paw magazine. The pictures aside, this issue has a wonderful article on energy weapons",
"One crate of 200 rubber gaskets",
"Choke chain for training a dog sized pet",
"Set of four large, fluffy bath towels (Hilton resort) never used carefully folded and stored in a sealed box",
"Cheezy Poofs. A box of cheese flavored puffs. They are extremely good",
"Folding super sharp metal hacksaw (blade broken)",
"Insulted industrial asbestos boots",
"Damaged Rubber Doll. This inflatable rubber sex doll has a torn seam.",
"A one-liter bottle of pure scotch whisky (Circa 2042)",
"25 meters of electrical wire, four sets of electrical plugs, and wire strippers",
"A Mini-DVD recording of the last American Presidential address to the nation (vaguely referring to new data that indicates contact with extra-dimensional intelligent life)",
"Motorcycle helmet with full face visor",
"Five variable intensity light switches",
"Deck of Tragedic Cards. This is a deck of cards from a collectible card game",
"A brand spankin new set of Lawn Darts in mint condition",
"Weapon cleaning kit (missing bore rods)",
"Box of Miscellaneous light sockets",
"Titanium Pry bar (1 meter long)",
"Full-dress Generals uniform (Soviet Union era) Medals and ribbons included",
"Perfectly preserved set (sealed in plastic vacuum bags) of all volumes of the Advanced Dungeons and Dragons RPG by TSR, Inc. 1st edition hard covers",
"Fallout 2 Hintbook",
"Eight sets of Silver eating utensils",
"A large illustrated book of Pre-rifts birds",
"fifteen meters of garden hose with a sprinkler attachment",
"One gross of men’s athletic socks (brand new, assorted sizes) – (Haynes)",
"Box of Rubber bands (dried out assorted sizes)",
"UV/IR goggles (cracked lenses) but operational",
"Travel cage for cat sized animal",
"1 Thermos brand cooler",
"A sealed 4 liter can of butterscotch syrup",
"Spray can of rust remover",
"Optical music chip of Vanilla Ice’s son making his record-breaking rock-rap debut",
"A set of Five cook books: vegetables, meats, chocolate deserts, breads, and cooking with herbs and spices (over 100 recipes total)",
"A case of 24 Li-ion photo batteries",
"Thermometer / barometer desk set",
"Six meter long metal tape measure (numbers faded off)",
"Hearing aid (broken, if used will cause temporary deafness in ear)",
"Manual on plumbing",
"Twelve bottles of assorted herbs and spices (un-tainted)",
"Box of 30 red Jimmy Hats, Thanks Captain_Chaos",
"pocket sized Spanish dictionary (brittle pages)",
"Three oil lamps (missing wicks)",
"A wireless keyboard from a Mac G7 (complete with a small retractable mini-screen for when you’re typing on the go, so you can hot sync with your computer later on).", 
"G.E.C.K - This unit is standard equipment for al Vault-Tec vaults.",
"Manual on how too use signal flares",
"Howitzer Shell. A 75mm Howitzer shell. The casing has mostly corroded away",
"Mirrored Shades. This is a pair of fashionable and deadly-looking mirrored shades",
"Mr. Nixon Doll. You see a small doll with a big red nose. For some reason, you don’t trust this seemingly-innocent child’s toy",
"Human Brain. A typical human brain. Normally they are found in human skulls",
"Magic 8-Ball. This black sphere is some strange precognitive device… A small window on the top seems to be able to predict the future! Pre-Rifts humanity must have been geniuses to invent such a wonder!",
"Role of Duct Tape",
"50 meter role of Bubble wrap",
"Movie “Fast Times at Rigemont High” Beta-Max edition",
"Twinkies (box of twelve, still edible)",
"One black and white photograph of Darklord DC (faded)",
"Dull Vibro-Blade (battery missing)",
"Copy of Chaos Earth (Burnt with a few pages missing, Incomplete edition)08: Pair of broken Finger nail clippers",
"Timex Expedition wristwatch (still ticking)",
"One Blank CDR still in plastic case (scratched)",
"Porcelain Doll of Emperor Prosek the 1st in body armor(when squeezed says “Mommy”)",
"Book “Forbidden Knowledge” by Stephen R. Donaldson (good condition, missing last page)",
"Stapler with staples a little rusty but usable",
"Colt .45 Gold Cup 2076 tri-Centennial Edition Pistol (excellent working condition still in walnut box)",
"Rusty Grappling Hook (looks usable, but will break after first use",
"Pack of After Burner Gum. After Burner gum is a powerful methamphetamine chewing gum that stimulates the central nerve system. The initial euphoric rush rarely lasts for more than a few minutes, but during that time, the user is filled with a rush of energy & strength.",
"Dented Stainless Steel Salad Bowl",
"A basic backpack, with optional carrying straps",
"Copy Of After the Bomb RPG signed by Kevin Siembieda (contraband worth 10,000 credits)",
"Case of pre-war Heineken beer only warmer",
"Bucket-O’Cockroach Guts. Useful in the treatment of radiation poisoning. Tastes like chicken, but it sure don’t feel like it",
"A set of locksmith tools. Includes all the necessary picks and tension wrenches to open conventional pin and tumbler locks",
"Field Medic First Aid Kit. A small kit containing basic emergency medical equipment. Bandages, wraps, antiseptic spray, and more (the antiseptic spray is poisonous to the touch)",
"First Aid Book. A study book on the concepts and practical use of first aid skills",
"Book “Zen and you/The Art of Piloting” Essential reading for anyone who wants to advance their driving skills (+10% to any piloting skill when completed, normally takes 1 week)",
"Yellow Coka-Cola. A little known flavor of Coka-Cola which is only available from the “crazy naked man”.",
"Plastique Exposive, or Cordex, a military brand of plastic explosives. Highly stable, very destructive Includes a timer",
"Bottle of Coka-Cola the flavored soft drink of the pre-rifts world. Warm and flat",
"A wooden axe handle. It would do more damage if the blade was still attached but it is still a useful weapon",
"A Broken Bottle, The preferred weapon for advocates of the drunken brawl",
"A large hammer with big handle. Very popular with the muscular crowd",
"DakTarg. A knife Weapon constructed for a bunch of obsessive TV fans in the 20 century. It works like a real weapon which is very sad.",
"Piece of Iron Pipe. A short length of lead pipe. Useful for plumbing or pummeling",
"Rusty Old Monkey wrench, used by mechanics for hurting people",
"Scalpel with a nicely made surgical steel blade. Very sharp",
"Louisville Slugger. This all America, hardwood, baseball-bat will knock anything right out of the park",
"Box of 100 assorted Rocks. Granite Inc. is an upgraded model",
"Flamer Pistol. A poorly designed, misconceived weapon. Essentially a cut-down version of the Flambe 450. Amuse your friends as you set yourself and everything around you ablaze",
"Ancient Computer System (commodore 64) –30% computer skills check to figure out how it works",
"Book, A copy of Adolf Hitler’s “Mein Kampf” (Joseph Prosek edition)",
"Box of 30 rusty map tacks",
"Set of 12 plastic drinking cups",
"Set of 4 Good year “Infinitred” Tires (no rims)",
"Individually wrapped Swiss Cake Rolls (5 total Poisonous if eaten –3 saving throw, but boy do they look tasty)",
"Movie “Grease” 8mm reel version",
"Ruger Mini .14, a 5.56 mm assault rifle originally only used by police forces, but also popular on the open market. A large magazine and full auto fire makes this weapon a real crowd pleaser… (75 round magazine missing, single-burst-and full auto rate of fire modes)",
"well-worn golden locket opens to reveal a charming picture",
"A questionable sexual device. If you need to ask, you don’t want to know",
"A chunk of Uranium Ore, unrefined.",
"Glitterboy Plans. A set of plans for building the all original Glitterboy! Woo hoo!",
"A grey and Blue Water Flask. This relic of the ancients was probably used to contain some sacred sacrament",
"Book “The Lavender Flower. It appears to be some kind of romance novel written by Dorothy RIXON. The cover has a woman laying on a bed surrounded by a hundred flowers",
"Small Statuette. You think this might be a carving of Mr. House or Caesar... or Kimball. You just can't tell.",
"A television dinner. You’re not sure, but it is definitely not edible. You’re not quite sure if it ever was",
"Case of 12 T45LE Mines. Will blow a medium sized vehicle several meters into the air",
"There is in excess of 1000 bottle caps to be found here",
"A banged up motion detector.",
"A rusty railroad spike",
"A set of Infinity Car Audio Speakers",
"Copy of Playboy magazine circa 2099 New Years edition (subscribers edition)",
"Some sort of toy space rocket. It faintly glows.",
"Set of useless brass assorted Keys",
"Box of Latex Rubber gloves (10 pairs)",
"Monopoly Game (star wars edition, missing pieces)",
"Box of 14 formatted holodisks with write-on lables",
"1 Broken picture frame",
"Box of assorted 20th century coins 30 coins total",
"Blister pack of Rifts Miniatures (Conversion Borgs)",
"Perfectly preserved set (sealed in plastic vacuum bags) X-men comics all issues up to the time of the Rifts",
"Broken 56K external computer modem",
"workable compass",
"Gas mask (filter needs to be replaced)",
"Book Copy of “The Bible” (insert version here)",
"Book “Historical sites of San Francisco” (covers slightly warped, but otherwise in good condition)",
"Post Card from the moon",
"1 Reebok sneaker (missing laces)",
"You find a picture of Elvis shaking hands with Velvis. On the picture you make out a cold stamp 'Property of Area-51. Return if found'",
"Book “Collier’s Wonder Book” 1st printing circa 1920 (If any of you have ever seen this book in real life let me know -Carter)",
"old Stop sign (excellent condition)",
"Copy of time magazine circa November 2098",
"Star Wars Episode IX “The Last Command” on Mini-DVD (good condition)",
"Book “Hitchhikers Guide To The Galaxy” in good condition",
"Copy of “Transformers the Movie” on VHS",
"1 Bar of Solid Gold (printed on bar “federal gold reserve of New York)",
"1 Bar of Solid Lead (¿?)",
"1 Bar of Scented bath Soap",
"1 bar of Hershey’s Chocolate, (eat at own risk)",
"SAMAS power armor wing (fully functional just needs the rest of the suit)",
"Rotten Meat",
"Old optical computer mouse",
"A strange bright green device with the word “Alienware” written on it. It appears to be some kind of technical device, but what does it do?",
"Mummified human hand",
"1 Spork and a can of Spam (edible)",
"Stuffed plush teddy bear (brown in color)",
"Computer Printer (broken)",
"A childs doll made with straw and cloth. It wears a dark blue with yellow strands.",
"Book “The Dragon Riders of Pern” by Ann McCaffrey",
"Easter Egg. This is a hard boiled chicken", 
"Mad Max wind-up music box (prop from the movie)",
"Verizon Cell Phone (Broken, Missing antennae)",
"Box Of Pentium 5 processors – 5Mhz / 2Mhz FSB / 2MB L2 Cache (still sealed in plastic) 10 processors total",
"Cattle Prod, A Farmer’s Best Friend model cattle prod from Wattz Electronics",
"Purple Rabbits foot attached to a brass chain with a broken clasp",
"A Black belt…perfect condition, still in the plastic next to a pile of scrap cloth that appears to be various colored belts that didn’t last. There’s also a small slip of paper (the shiny coated kind) with a rough step-by-step diagram on how to tie the belt properly",
"Neds Atomic Dustbin. What is does, though, is up for debate",
"Large dusty bear rug brown in color but still functional (needs cleaning)",
"Box full of 20 assorted Metallic Rings with various jewels and gems in them (20 rings total various sizes rings are made of gold and silver 18 Karrot)",
"Package of Bic ball point pens (yep they still write on the first try (12 pens in package)",
"“Little Jesus”, This wicked looking blade once belonged to Lil’ Jesus Mordino™. Perhaps not this one but it is a nice switch blade",
"A faded black Karate Gi with a cobra patch on the back. The pants are dusty but OK, and the jacket has some serious mildew on the lower left portion",
"Gold Tooth. This gold tooth used to belong to somebody, but it’s yours now.",
"Prosthetic hand (exceptional quality can still be used, needs Cyberdoc)",
"Role of Carpet light brown (40’ x 100’ roll) no padding",
"Old black hand-held transistor radio with telescoping antenna (strange but is still pics up transmissions from the 70’s and only plays disco music, The Horror!)",
"Glitterboy toy! it is a 12” model of the real thing with removable pilot, and “realistic” “Boom gun action”™ and “Boom sound”™",
"Naked Moose Mag, An under the counter magazine featuring the finest moose flesh in the land. The articles are exceptional",
"Box of Salt & Pepper Shakers (pepper bad but the salt can still be used)",
"Box of paper plates (they crumble to dust when handled)",
"Bottle of Bleach (full, still sealed never opened) label has worn off so the characters may not know what it is",
"Leather office chair (leather is worn hardened and cracked in places) 23: Box of Paperclips (88 clips total)",
"A pair of Nunchaku with the one of the wooden handles rotting away, and the other is petrified",
"An inflatable rubber sex doll. This model is called “Tandi”",
"Box of 100 Cool mint Listerine PocketPaks™ (oral care strips / 24 per pack) your characters will never have bad breath again!",
"1 broken flat head screwdriver",
"Flawless quarts crystal necklace",
"Old Leathery Book “The Necronomicon” (Latin translation / fifteenth century black-letter edition) No identifiable Markings as too what this book may be",
"Box of Colorful Silk ribbons of various lengths (300 ribbons total none over 12 inches in thength)",
"Cthulhu Plush stuffed toy",
"Old Leather Bombers jacket (leather needs some care but is XXXXL in size (will fit most humanoid borgs)",
"The complete 5 season collection of “Monster Garage” on DVD (oh the possibilities!)",
"A stash of Jet and Pyscho. Perhaps they get better with age.",
"“The Book of Ten™”: The book itself is an unassuming, leather-bound tome about the thickness of a phonebook. The thousand pages within are the thickness of onionskin",
"Box of 12 pure silver Sporks!",
"Yog-Sothoth Plush Stuffed toy",
"Thermaltake 8mm computer case fan",
"Package of nylon shoelaces",
"Box of 20 Fusion Batterys, A sophisticated power storage device, compatible with many “Pre-Rifts” artifacts",
"Maxim Magazine Nov. 2238 edition Cover article “Brittney Spears Daughter Caught nude!”",
"Wind-up Patriot Action Toy (walks around saying “The Enclave is your friend” and “Destroy all non-humans”). Black in color",
"A perfectly folded Post Size American Flag in Pristine condition, in a triangular Glass and wooden frame",
"Bag-O’ army men (100 little green plastic army men)",
"A set of 4 DVD cases with the label rotted away (some cases are in very poor condition). Opening the cases reveals the titles: “And1 MixTape” Volumes 3, 5, 6 and 8",
"A torus. Your guess is as good as any.",
"Cybernetic Gyro-Compass (looks like it may have been used)",
"Model 3000 Police Smith & Wesson Shotgun: This is fairly typical of pump action shotguns used by police for riot control. (It is in fair condition but is missing it’s trigger",
"Box of 12 gauge Shotgun rounds 00-Buck (12 rounds, 4 will crumble when handled)",
"The missing Trigger for number 48",
"A Wattz Electronic Micromanipulator FingerStuff electronic lockpick. For defeating electronic locks and security devices (broken, also needs a battery)",
"A 6 foot high trophy made of plastics with a socket for a small bulb in the “body” of the trophy with a little plastic guy doing a technically inaccurate side kick",
"Multi-Optics Helmet: The multi-optics helmet is a special optical enhancement system built into a protective helmet. Child sized.",
"Led Zeppelin Album on 8 track tape",
"Copy of PC Gamer Magazine Oct. 2274 edition, Cover Article “Sony Online Goes Bankrupt”",
"Conventional Binoculars Left lens broken",
"Mini-DVD computer game “Rifts” Macintosh OS XX version",
"Book “How to win Friends and influence people” poor condition / handle with care",
"A chocolate chip cookie. Yum! (Petrified, can be used as melee weapon, maybe)",
"Medical Kitç Not effective against internal injury, broken bone, or severe wounds. But great for cuts, bruises, bullet and stab wounds",
"Slap Gloves, Six ounces of powdered lead is built into each glove just above the knuckles padding the wearer and adding weight and strength to the force of one blow",
"Old vehicle that’s too broken down to fix but is good for parts",
"Hal 9000 Personal Data Assistant (it even says “Good Morning –insert name here-” every time you turn it on)",
"Authentic Kevin Long Painting of the “Ley Line Walker” worth 1,000,000 credits",
"Pair of walkie-talkies (need batteries, but still work 3 mile range)",
"HI-B3 Heavy Infantry Armor Painted to look tie-died. Needs some repairs is obviously used",
"Holotape. This holotapes is a data storage disk, based on Tape Holography technology, storing its information safe for extended periods of time. This disk can be read by the PIPBoy 2000 Personal Data Assistant",
"Fusion Block type III, Looks functional in every way but will explode the second it is used",
"SAMAS helmet missing an eyepiece, but otherwise still functional",
"Book “Traversing Our Modern World” By Erin Tarn (Excellent Condition)",
"Bag of Scented Bath Beads (Lavender Scent)",
"E-Tool (handle bent slightly)",
"Camouflage Gore-Tex Jacket with lots of pockets and a hood size XXL 76: Box of green cyalume® Lights Sticks (40 sticks)",
"10 cans of German instrument grease",
"Box of 20 rusted P-38 Can openers",
"Crate of 100 Individually wrapped White Haynes T-Shirts (still in Plastic) 81: 2 Full Bottles of US military issue Insect repellent (be careful this stuff will melt some plastics!)",
"A pair of almost new OpticalVidChips still in the original plastic. “And1 MixChip” Volume 1 and 2 (Juicer Basketball, when the harness was big in the streetball games…If the characters can get their hands on a viewer, they will be blown away by the speed, dribbling skills and insane dunks [on a 20 foot rim] that these players are capable of…they will also find it disturbing that the average age of the players is 17, the price of fame)",
"British Military Zulu Helmet (white in color)",
"1 Broken Yo-Yo",
"1 Hoola-Hoop Bright red in good condition",
"Crate of Leather Combat boots (Gore-Tex) 20 pairs in various sizes. Danner Brand",
"Brand new Chess set still in Box (Missing 1 white pawn, and the Black queen piece is partially Melted)",
"Wind-Proof butane Lighter (works, but needs fuel)",
"Electric Nose hair trimmer! Needs a battery",
"Box of Well made Stainless steel Throwing Stars (2d6 sdc damage) 10 Stars",
"Techno-wizard Flaming Sword,",
"Barnet 150-lb Ranger Cross bow (missing String)",
"A Tupac CD with all new material, released in 2012 AD (this one hits the charts high, and brings about a whole slew of rumors that 2Pac is still alive)",
"Silver Zippo Lighter with U.S. Marine Corps Emblem in 24 Karat Gold (needs Fuel)",
"Set if Vinyl Window Blinds (Cracked)",
"Leather Steering wheel for a 2069 model Corvette (good condition)",
"California License Plate",
"A pair of porcelain fangs (cracked and chipped…poor condition) that appear to have fallen off of a skull laying next to them",
"Water wings (suitable for use in the CS Navy)",
"Box of ex-lax (still Good)",
"Reddi-Whip Whipping Cream (in a can)",
"A package of Plain M&Ms You could win a million dollars --- see inside!",
"You find a Sears Catalog (cover missing) circa 2098",
"A stage makeup kit",
"A cell phone (out of range)",
"A package of 6 “chap sticks",
"A Webster’s Dictionary 57th Edition (2098)",
"Some Bath and Bodyworks Honeysuckle Body Lotion",
"ROBOTECH II the Sentinels VHS, episodes 4 through 21- Episodes 1, 2, and 3 are missing",
"A local Newspaper (wherever the PC are at) dated Dec 22 2098",
"Tube of crazy glue",
"An unpaid phone bill to the cell phone above…",
"You find a jar of paste (half-eaten)",
"A water faucet, or a drinking fountain (does not work / this is especially good if your characters are in the desert…)",
"Beaded car seat covers",
"A roll of stamps (3.50 variety), but they are the kind you have to lick",
"Instruction book for a VCR (the section on how to set the time is highlighted for some reason…)",
"Car seat, leather (missing car)",
"Television remote no batteries",
"8 track player (car not included) missing knobs and buttons",
"Naked Barbie doll",
"Box of yellow smiley face stickers --- the smelly kind",
"A Dwarf Hamster in cage (dead -NOT edible)",
"A Kirby vacuum cleaner circa 1999 no cord.",
"A bag of empty coke cans ($0.10 each in MI)",
"A “Jordan Jammer” basket ball net. Basket Ball not included",
"Basket ball (missing air) grip warn off",
"A piece of Driftwood",
"A couch. no cushions",
"A La-Z-Boy recliner (foot rest missing)",
"Plush Maryann stuffed toy",
"You find 50 experience points (game master missing)",
"You find Plans to the Death Star",
"Bullet Resistant Attaché Case",
"Candle Stick, per box of 12",
"Padlock, on its own.",
"A small stuffed toy, it looks like a small Dee-bee child, made of some type of foam, it has (30%chance) a blue T-shirt on and (40%chance) a pair of shorts, it also has a “ring-pull” on it’s back (when pulled there is a 30% chance that it works, and it says things like; “eat my shorts” and “I-cerumba!”)",
"1D4 small tubs of shoe polish, still sealed (60% black, 30% brown or 10% chance something else or is un-usable)",
"Winter Survival Kit: A winter survival kit is a light metal box. Contains 3 hand-held flares, one smoke grenade, signal mirror, box of 36 waterproof matches, a cigarette lighter, 6 sterno canisters, folded thermo-blanket, 4 heat packs (the size of a paperback novel; each lasts 4 hours), freeze-dried food and vitamins for seven days, 16 concentrated fat pills, an extra pair of thick mittens, pair of thick socks, a ski mask, scarf, tinted goggles, pocket knife, and a hand axe and a Rubik’s Cube",
"A 4lb. Piece of Red Kryptonite",
"Box of six Golf balls (new)",
"A Box of bubble-gum! 1D10 packets of ten are still good, the rest are not so good (cause nausea on a failed save, minus one to strike parry and dodge for 1D4hrs, and loss of gum lunch etc [this also makes you easy to track…eeeew… poor dog packs!)",
"Baseball signed by Mark McGuire (sp)",
"Set of Used Rollerblades (good condition)",
"Book “Sid Meier’s Alpha Centauri” Strategy Guide by Prima. (Worn condition)",
"Book “Accounting by Enron” Lower math skills by 1% (cursed Item)",
"False teeth, a Pacemaker, and a doll that says in an eerie voice “Ma-Ma”",
"Solid Gold Ring (looks like any other unadorned ring, but when held to a fire mysterious writing appears along the whole length of the band) will shrink to fit the size of the owner",
"Book, “How to be a Webmaster” by Midnght",
"Box of multi-colored women’s Thong underwear by Victoria’s secret",
"Periscope (kids toy) 2meters in length",
"A Beta Max Copy of Planet of the Apes, the Original Theatrical version",
"A Bag full of 2000 gold Sacagawea dollar coins (Circa 2000) This bag features dollar coins struck on the main production floor at the Philadelphia Mint facility",
"Badly faded Matrix Revolutions Movie poster",
"Hunting and Fishing Kit: Wires, fishing line and several hooks and pulleys, useful for both fishing and setting snares for small game",
"“Dilbert” Desk Calendar for the year 2098",
"Plastic Fold up Rand McNally’s road Map of the United states. (horribly outdated)",
"Chia pet kit (unused)",
"Black and white Plush Darklord DC stuffed toy",
"You find the Internet (It has been disconnected)",
"Book “Fundamentals of Physics” by A. Einstein revised edition circa 1956",
"Spider man movie costume",
"1 set of leather bikers chaps",
"1 box of coffee dairy creamer",
"Plastic Fold Up Rand McNally’s road Map of Chicago Il, circa 2097",
"1 crate full of 1000 bags of chicken flavored Ramen noodles. Still edible",
"Flashlight, Rechargeable & Unbreakable: Is ten times brighter than most conventional types.",
"Bag of multi-colored marbles",
"A few loose screws.",
"A rusty box of old tools (1D4X200credits worth is salvageable)",
"1 rusty car muffler",
"The Holy Grail",
"1 large Aluminum garbage can. (Dented, missing lid)",
"1 Shotgun Shell",
"Box of Clay pigeons",
"You find a large Wooden Crate dated Circa 1939 Stamped Top Secret U.S. Government.",
"Arnold Schwarzenegger’s Accent",
"Larry Flint’s Wheelchair",
"NG-S2 Basic Survival Pack: A very popular item among adventurers and other travelers, the NG-S2 survival pack contains all the basic things someone traveling through the wilderness could need. (Empty)",
"Soundtrack to “2001 a space odyssey” on CD",
"1 Mickey mouse neck tie",
"A Build it yourself model of some sort of pre-rifts vehicle (box is badly damaged, but it’s contents are ok, though the instructions are not!)",
"A doll.",
"1 Flux Capacitor (brand new in box)",
"Set of Broken Bag Pipes (can be fixed)",
"1 shiny box with just 2 letters on it: S&M.",
"1 “Jack in the Box” Hard Foam Antenna ball",
"Box (cardboard, falling apart) full of individually wrapped Nightbane T-shirts, assorted sizes",
"Book, copy of “Cooking with Geronimo” (excellent condition, written in a New Orleans Drawl)",
"An old pre-rifts “car” key in good condition… though there is no car to be found within 1D6 miles that it MIGHT fit",
"1 U.S. Army black Beret Worn with age but still serviceable",
"1 Boy scouts of America Patch (slightly faded)",
"A paperback book, it is small and red, the inside has some strange symbols in it (“oriental” to those who know), could be considered “Dee-bee” contraband!",
"Petrified Brownie",
"Book “RIFTS®” by Palladium Books First Printing Circa 1990 (Soft cover, Mint Condition in Plastic Wrap)",
"A small cube shape, elaborately decorated version of a “puzzle box”? (Can only be used by those who can use TW devices! …But what happens when you complete the puzzle?!",
"The Necronomicon on CD-Rom",
"High quality photograph taken of the Earth from the Moon",
"DVD “Air-Supply’s Greatest Hits in Concert” circa 2009",
"Book “The Prydain Chronicles” by Lloyd Alexander (excellent condition)",
"Box of 20 Remington Center fire 30-40 Krag Core-Lokt Rifle cartridges (brass needs cleaning but otherwise still in good condition)",
"Moon Rock",
"Book “Supernatural Horror In Literature” by H.P. Lovecraft Written 1926-27, Revised 1933",
"Vinyl Album “Black Sabbath”",
"Graduation Tassel class of 2098",
"Enron Accounting Book revised edition.",
"Portable tombstone: So your friends can mark your grave when you become frag meat",
"Case of Body Rehabilitation Injections: restores 3D6 Hit points per injection at a rate of one per minute, these can heal critical wounds: 100 injectors",
"Box of Mentant Tablets: These Wonderbar drugs shorten the time required for messages to cross the neural synapses in the central nervous system in humans only",
"Case of Mountain Dew Soft Drinks in cans, 10 redeemable in Michigan after consumption) 24 cans",
"You find Yourself",
"You find a “PC Load Letter”",
"You find three words written in Broken English on a sheet of weathered parchment “Klaatu Barrada Nikto",
"You find Ash’s Hand (slightly mummified, but if you find a good cyberdoc he may be able too hook you up)",
"You find a Bright red 03’ Ford Mustang Convertible in brand new condition stashed away somewhere GM’s discretion; Needs Fuel",
"A statute of Falcon less than a foot high, covered in black enamel. Chipping off the enamel will reveal what lies beneath… What is it? The stuff that dreams are made of",
"Excalibur: Yup the real deal I guess this means you are the true king of England, Better get packing it’s a long swim. Comes with scabbard",
"Broken Iomega Zip Drive",
"Anime “Legend of the Overfiend” on Mini-DVD format",
"Copy of Evil Dead I and II on DVD special Edition Set.",
"An autographed copy of Mein Kampf.",
"Anime “Return of the Overfiend” on Mini-DVD format",
"Copy of the Rifter 9½ (good condition, excpet that the cover is missing)",
"Quarrels for the special forces crossbow",
"Colt 1911A1 Auto-Pistol Gold Plated with the Words The Deific NMI inscribed on the slide (weapon is functional)",
"The Holy Hand Grenade of Antioch! Absolutely destroys ANYTHING that it is thrown at, with a blast radius of 20 feet! Downside- You HAVE TO FOLLOW THE DIRECTIONS, which weren’t included",
"A tin case that says on the cover “Aol 8.0 1045 hours free!”: if opened the players will have 43.5 days added on to their natural lives.",
"Book: “The Colour out of Space” by H. P. Lovecraft Written 1927",
"You find the Animatrix: Your character turns into the Anime form of himself, all stats and powers and equipment is affected also, just in Anime form",
"Movie: “Attack of the Killer Tomatoes!” (1978) On VHS",
"You find Austin Powers Wardrobe",
"You find Apollo 13, It is heavily damaged from some sort of explosion",
"You find Batman’s Costume from the first movie (1989)",
"Mel Gibson’s Sword from Braveheart",
"A DeLorean: Runs on Gasoline, Powered by Plutonium (missing Flux Capacitor)",
"A box of primary color acrylic paints (dried up)",
"One Timex digital watch, broken.",
"One unused prophylactic, soiled",
"Police Car: It’s got a cop motor, cop tires, cop suspensions, cop shocks. It is a toy!",
"Old Phone booth (missing Phone)",
"An Empty Spot",
"A small, half foot tall box containing either (1-50: Tux the Penguin Plushy, 51-00: BSD Daemon Plushy). Mint Condition",
"You find a mission from God",
"A full tank of gas",
"Half a pack of cigarettes",
"Two pair of sunglasses",
"you Acquire Merlin’s Advice",
"A Johnny Cash T-shirt (ripped)",
"9th dimensional bomb: There goes the galaxy (If you don’t know what this device is watch the movie Supernova with James Spader (2000)",
"You find a Baby Deathclaw",
"Jason’s Hockey mask (GM pick which Jason flick to determine mask style)",
"Bag of loaded game dice",
"Pinhead Doll",
"Connor MacLeod’s Katana with scabbard",
"Scream Movie costume",
"A crate of 20 colt 45 revolvers (all the hammers have been filed down and barrels filled with lead)",
"Bag of Rabid Weasels (5 Weasels included)",
"Brand new Burton Snow board",
"Elvis Costume complete with wig",
"tube of Revlon Lipstick (used, solid as a rock)",
"lump of coal",
"bag of twist ties",
"Star Wars Episode IIX “Dark Force Rising” on Mini-DVD (good condition)",
"Busted computer keyboard",
"Empty CD jewelcase",
"Can of gloss white paint (dried up)",
"You find the Andromeda Strain: All of your characters blood is turned to powder! (role a new Character)",
"1 Pup Scout Reconnaissance Drone (New in Box) – (Missing Nuclear Power Source) - (see page 77 Rifts: Chaos Earth for details)",
"Darth Mauls Light Saber (fully functional weapon, GM can decide the stats)",
"Ash’s *boom stick* A 12-gauge double-barreled Remington. S-Mart’s top of the line. You can find it in the sporting goods department. That’s right, this sweet baby was made in Grand Rapids, Michigan. Retails for about $109.95. It’s got a walnut stock, cobalt blue steel, and a hair trigger. That’s right. Shop smart. Shop S-Mart!",
"Full suit of Old style Coalition Dead Boy body armor (missing Helmet)",
"A Latin Bible (2000 years old)",
"3DFx Voodoo 3 3000 AGP PC Graphics accelerator card (New in Box, Mint Condition)",
"1 metal coat hanger (rusty)",
"Old Style Coalition Dead Boy Body Armor Helmet (used)",
"Johnny Bravo Life sized ceramic statue",
"The Book of Nod: An ancient, pre-rifts book declaring itself to be the history and prophesies of a race of vampires descended from the first murderer! Includes details of wars between various subgroups, origin mythology, and an allegorical account of the End of the World",
"Case of Campbell’s Chicken Noodle Soup (20 cans, still edible if heated)",
"Block of Petrified Cheddar Cheese (wrapper says made in Wisconsin, sell by 11-26-03)",
"An ancient relic caller the “Cartor” worshiped by an ancient civilization"];

/* Fallout Weapons */
/* Handmade Guns */
var handmade = ["Pipe Pistol - Break Action 9mm",
"Pipe Rifle - Break Action 9mm",
"Pipe Rifle - Break Action 10mm",
"Pipe Rifle - Bolt Action 10mm",
"Shotgonne - Breach Load .44"];
/* Pre-historic crap */
var lamepistols = ["Browning Hi-Power - 9mm",
"Barretta 92fs - 9mm",
"HSI Mauser - 9mm",
"P220 Sig Sauer - 9mm",
"NC99 - 10mm",
"Colt Delta Elite - 10mm",
"Colt M1911 .45 - .45",
"Casull Revolver - .45",
"Desert Eagle .50 - .50 AE",
"Desert Eagle .44 - .44",
"Smith & Wesson Model 29 - .44",
"Colt Python - .357",
"Mateba Autorevolver - .357",
"Glock 20 - 10mm"];
var lamesmgs = ["MP5 - 9mm",
"MP9 - 10mm",
"Tommy Gun - .45",
"Walther MPL - 9mm",
"Mini Uzi - 9mm",
"Uzi - 10mm",
"P90 - 5.56mm",
"Grease Gun - .45"];
var lamerifle = ["Varmint rifle - 5.56mm",
"Hunting rifle - 7.62mm",
"Hunting rifle - .50",
"Ak-112 - 5.56mm",
"Service Rifle - 5.56mm",
"Lever Action - .357"];
var lamemelee = ["Shiv - Rusted",
"Knife - Utensil",
"Knife - Butcher",
"4x4 Board",
"4x4 Board - Nail1",
"Trench Shovel -Rusted",
"Pipe - Water",
"Baseball bat - Wooden",
"Baseball bat - Aliminum",
"Pole - Wooden",
"Pole - Metal",
"Shiv - Broken Edge"];
var lameexplosives = ["Firecrackers",
"Box Of Firecrackers",
"Fireworks",
"Fireworks Bundle",
"Molotov Cocktail - Half Empty",
"Molotov Cocktail - Dried",
"Dynamite Stick",
"Homemade Fertilizer Grenade",
"Homemade Fertilizer - Satchel"];



/* Weapon Conditions */
var firearmcondition = ["Jammed - Rusted",
"Jammed - Misfed, Deformed Loading Mechanism",
"Jammed - Obstructed By Debris",
"Rusted - Beyond Repair",
"Rusted - Salvage",
"Rusted - Fixable",
"Missing Part - Trigger",
"Missing Part - Shattered Muzzle",
"Missing Part - Striker",
"Missing Part - Broken in half",
"Missing Part - Furniture & Body",
"Missing Part - Loading Spring",
"Debris - Melted",
"Debris - Radioactive",
"Servicable - Well Maintained",
"Servicable - Sealed In Plastic Bag",
"Servicable - Recently Fired",
"Servicable - Freshly Oiled",
"Good as new",
"Mint Condition",
"Mint Condition - All Accessories",
"Mint Condition - Still in its case"];

var explosiveconditions = ["Bad Fuse",
"Corroded",
"Wet",
"Missing - Half",
"Missing - Broken Casing",
"Single",
"Ready to go",
"Mint",
"In Military Case",
"Armed",
"Ingredients - Missing Fuse",
"Ingredients - Including Recipe",
"Ingredients - Just Chemical Jars",
"Ingredients - Missing Casing",
"Military Crate"];

/* "M-160 - 7.62";
Colt 6520 pistol */
function clearelements() {
	document.getElementById("G1").innerHTML = "";
	document.getElementById("G2").innerHTML = "";
	document.getElementById("G3").innerHTML = "";
}

function rollD6() {
	var s = Math.round(Math.random()*5);
	s += 1;
	document.getElementById("G0").innerHTML = s;	
	}

function trashloot(num) {
	clear();
	if (num == -1) {
			var aa = document.getElementById('value').value;
		}
	else {
			var aa = num;
		}
	var s =  "<ul style=\"list-style-type:circle\">";
	for (i = 0; i < aa; i++) {
		var r = Math.round(Math.random()*689);
		s += "<li>" + trashlist[r] + "</li>"
		}
	document.getElementById("G1").innerHTML = s + "</ul>";	
	}
	
function printresult(s1, el1, s2, el2) {	
	
		clearelements();
		document.getElementById(el1).innerHTML = "<ol type=\"1\">" + s1 + "</ol>";	
		document.getElementById(el2).innerHTML = "<ol type=\"1\">" + s2 + "</ol>";	
}

function generatefromtype (type, num) {
	var a = megamixer(type, num);
	printresult(a[0], "G2", a[1], "G3");
}

function megamixer(type, num){

	var s = "";
	var s2 = "";
	if (type == -1){
		var r = Math.round(Math.random()*5);
	}
	else {
		var r = type;
	}
	
		var n = num;
	if (num == -1){
		var n = 6;
	}

	
	for (i = 0; i < n; i++) {
		switch(r) {
			case (r = 0):
				/* this case is for handmade */
				s += "<li>" + handmade[Math.floor(Math.random()*(handmade.length - 1) + 1)] + "</li>";
				s2 += "<li>" + firearmcondition[Math.floor(Math.random()*(firearmcondition.length - 1) + 1)] + "</li>";
			break;
			case (r = 1):
				/* this case is for lamepistols */
				s += "<li>" + lamepistols[Math.floor(Math.random()*(lamepistols.length - 1) + 1)] + "</li>";
				s2 += "<li>" + firearmcondition[Math.floor(Math.random()*(firearmcondition.length - 1) + 1)] + "</li>";
			break;
			case (r = 2):
				/* this case is for lamesmgs */
				s += "<li>" + lamesmgs[Math.floor(Math.random()*(lamesmgs.length - 1) + 1)] + "</li>";
				s2 += "<li>" + firearmcondition[Math.floor(Math.random()*(firearmcondition.length - 1) + 1)] + "</li>";
			break;
			case (r = 3):
				/* this case is for lamerifle */
				s += "<li>" + lamerifle[Math.floor(Math.random()*(lamerifle.length - 1) + 1)] + "</li>";
				s2 += "<li>" + firearmcondition[Math.floor(Math.random()*(firearmcondition.length - 1) + 1)] + "</li>";
			break;
			case (r = 4):
				/* this case is for lamemelee */
				s += "<li>" + lamemelee[Math.floor(Math.random()*(lamemelee.length - 1) + 1)] + "</li>";
				s2 += "<li>" + firearmcondition[Math.floor(Math.random()*(firearmcondition.length - 1) + 1)] + "</li>";
				break;
			case (r = 5):
				/* this case is for lameexplosives */
				s += "<li>" + lameexplosives[Math.floor(Math.random()*(lameexplosives.length -1) +1)] + "</li>";
				s2 += "<li>" + explosiveconditions[Math.floor(Math.random()*(explosiveconditions.length - 1) + 1)] + "</li>";
				break;
		}

	}
		var res = [s , s2];
		return res;
}


